version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: sagis-app
        container_name: sagis_app
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html:z
            - ./storage:/var/www/html/storage:z
        extra_hosts:
            - "host.containers.internal:host-gateway"
        environment:
            APP_NAME: "${APP_NAME}"
            APP_ENV: "${APP_ENV}"
            APP_DEBUG: "${APP_DEBUG}"
            APP_URL: "${APP_URL}"
            DB_CONNECTION: pgsql
            DB_HOST: host.containers.internal
            DB_PORT: 5432
            DB_DATABASE: "${DB_DATABASE}"
            DB_USERNAME: "${DB_USERNAME}"
            DB_PASSWORD: "${DB_PASSWORD}"
            MAIL_MAILER: "${MAIL_MAILER}"
            MAIL_HOST: "${MAIL_HOST}"
            MAIL_PORT: "${MAIL_PORT}"
            MAIL_USERNAME: "${MAIL_USERNAME}"
            MAIL_PASSWORD: "${MAIL_PASSWORD}"
            MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"
            MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
            MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
        networks:
            - sagis-network

networks:
    sagis-network:
        driver: bridge
