version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sagis-app
    container_name: sagis_app
    restart: unless-stopped
    ports:
      - "${PORT_0}:80"
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: pgsql
      DB_HOST: host.containers.internal
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
